### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by corysimmons** [spatie/npm-install-peers#15]
![image](https://user-images.githubusercontent.com/224636/29254276-e8da3fe8-805f-11e7-8d33-e68ff821ae0b.png)

**Comment by sebastiandedeyne** [comment]
What does your package.json file look like?

**Comment by sebastiandedeyne** [comment]
Note that this package installs your *current* project's peer dependencies for development, not the peer dependencies of your dependencies (which should be added to your project's dependencies)

**Comment by sebastiandedeyne** [comment]
Pretty sure that's the issue. Gonna close this since I'm doing an issue cleanup, feel free to reopen if you still have questions!

**Comment by ophite** [comment]
the same problem

**Comment by sebastiandedeyne** [comment]
Please share the contents of your package.json file so I can see what's going on.
