### ISSUE TITLE
Not supported by Node 0.12

### ISSUE THREAD

**Issue by dannyfritz** [spatie/npm-install-peers#2]
The ES6 features `const` and `class` prohibit this from being run on older version of Node.

This is making it hard to test this package on Travis for multiple versions of Node: https://travis-ci.org/eslint/typescript-eslint-parser/builds/161519098

**Comment by sebastiandedeyne** [comment]
I created an rc release that uses a transpiled script instead of raw ES6, could you give it a spin? Having some issues with my node installation at the moment.

```
npm install -g npm-install-peers@'1.0.1-rc.2'
```

**Comment by dannyfritz** [comment]
I don't think the release was built before it was published:

https://travis-ci.org/eslint/typescript-eslint-parser/jobs/162620048#L260

PR: https://github.com/spatie/npm-install-peers/pull/3

**Comment by dannyfritz** [comment]
Fixed in https://github.com/spatie/npm-install-peers/pull/3

Thanks @sebastiandedeyne!
