### ISSUE TITLE
Utterly baffling UI

### ISSUE THREAD

**Issue by lucasgonze** [spatie/npm-install-peers#22]
```
> npm-install-peers 

This package doesn't seem to have any peerDependencies

> npm-install-peers ajv-keywords

This package doesn't seem to have any peerDependencies

> npm-install-peers -h

This package doesn't seem to have any peerDependencies

> npm-install-peers --help

This package doesn't seem to have any peerDependencies

> npm-install-peers ajv-keywords

This package doesn't seem to have any peerDependencies

> npm-install-peers ajv

This package doesn't seem to have any peerDependencies

> npm-install-peers ajv-keywords@2.1.1

This package doesn't seem to have any peerDependencies
```

**Comment by sebastiandedeyne** [comment]
If you're having issues with this package, please provide a detailed explanation of what's going wrong, what you expect to see, and as many details as possible like node version, npm version and package.json contents.

**Comment by lucasgonze** [comment]
On running npm install, we get this:

`npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yoursel`

npm-install-peers is designed for exactly this situation, but:

`npm-install-peers` 
gives
`This package doesn't seem to have any peerDependencies`

I can be certain that there are indeed peer dependencies, because npm is telling me so. So the issue must be a user error - I need to learn the proper usage of npm-install-peers. As you can see in my original issue report, I have done plenty of trial and error without discovering any additional information.

There does not exist any documentation. Not in the project homepage on github, or in a usage message, or via a -h or --help flag, or in the error message itself, or even in this issue trail.

**Comment by sebastiandedeyne** [comment]
> npm-install-peers is designed for exactly this situation

It isn't. It's designed to install the direct peer dependencies of your project, not the peer dependencies of your dependencies. (also see #21)

I agree that this is a bit ambiguous in the readme and I'll clarify the scope of this package.

In the future, please consider posting a friendlier issue. A title like "Utterly baffling UI" doesn't really motivate maintainers to sacrifice their time on problem-solving.

**Comment by lucasgonze** [comment]
To say it's ambiguous in the readme is overstating the case. There is no reference at all to this point.

**Comment by lucasgonze** [comment]
Does the app take any arguments? What factors does it take into account?

**Comment by sebastiandedeyne** [comment]
The readme has been updated to clarify what this package does

https://github.com/spatie/npm-install-peers/commit/bb9a3c9956cf5152199bbce4f209b23043000f9d

**Comment by lucasgonze** [comment]
That's excellent.
