### ISSUE TITLE
Missing `escape-string-regexp` dep

### ISSUE THREAD

**Issue by moltar** [spatie/npm-install-peers#24]
```
❯ npm-install-peers -h
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module 'escape-string-regexp'
```

**Comment by sebastiandedeyne** [comment]
According to another issue I came across, it's probably a sign of an npm installation issue.

> This is usually a sign of some kind of npm install corruption. Ensure you're on the latest Node.js and npm version ($ npm i -g npm). Then delete the node_modules folder and run $ npm cache clean and then $ npm install. Use the npm issue tracker for support.

https://github.com/yeoman/generator-webapp/issues/423#issuecomment-160867799
