### ISSUE TITLE
throw new TypeError('must call as: npm.load(callback)') while runnint `npm-install-peers`

### ISSUE THREAD

**Issue by kheyali-mitra** [spatie/npm-install-peers#30]
Our team and I have started getting the following error when we run `npm-install-peers` 
```
/Users/kheyalimitra/code/pfm/node_modules/npm/lib/npm.js:130
      throw new TypeError('must call as: npm.load(callback)')
      ^
TypeError: must call as: npm.load(callback)
    at Object.load (/Users/kheyalimitra/code/pfm/node_modules/npm/lib/npm.js:130:13)
    at /Users/kheyalimitra/code/pfm/node_modules/npm-install-peers/dist/index.js:40:9
    at /Users/kheyalimitra/code/pfm/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
```
Our team uses `npm` version `6.14.1` not `7.x.x`. We suspect that could be the issue hence added a fix. 

![Screen Shot 2021-02-02 at 3 03 40 PM](https://user-images.githubusercontent.com/69566395/106674314-db498f00-6567-11eb-822b-a281886c37f9.png)
Let  me know what you all think. 
Thanks. 

### PR link:
https://github.com/spatie/npm-install-peers/pull/29

**Comment by hubiierik** [comment]
I am seeing the same issue, the builds of my company have started to fail today.
May not be relevant, but I offer the following observation:
* The dependency to npm in package,json is not constrained by version:  `"npm": "*"`
* The npm package 7.5.2 was updated yesterday a few hours before @kheyali-mitra submitted current issue.
  https://www.npmjs.com/package/npm/v/7.5.2

**Comment by henit** [comment]
I just got the same error. I was running `npm-install-peers@1.2.1`, upgraded to `1.2.2`, and the error disappeared
