### ISSUE TITLE
Feature Request: Write updated versions back to package.json

### ISSUE THREAD

**Issue by toddpi314** [spatie/npm-install-peers#4]
This is a great tool!
The next step is to write the updated versions back to the package.json where the primary use-case is "Blast! I need to update all of the peer deps and get my npm install working again.."

**Comment by sebastiandedeyne** [comment]
I'm most likely not going to implement this myself, but I'd accept a PR that adds this.

**Comment by sebastiandedeyne** [comment]
Bonus points if the PR adds tests 😁
