### ISSUE TITLE
Allow --no-bin-links

### ISSUE THREAD

**Issue by jehy** [spatie/npm-install-peers#6]
I am using virtual machine on windows, and I can't have symlinks. I always install deps with `--no-bin-links` flag. Could you please add this option to npm-install-peers?

It would also be cool to allow passing other options which are used with npm install.

**Comment by sebastiandedeyne** [comment]
Hi, I probably won't be able to add this any time soon since I'm working on other stuff.

However, I'd accept a PR that allows other options to be passed.

**Comment by jehy** [comment]
@sebastiandedeyne Thanks! Here it is: https://github.com/spatie/npm-install-peers/pull/7
Sorry for commit spam, I did not expect that references from fork would appear in parent repository...
